host:
  url: http://localhost:8080
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: false
    show-sql: false
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:tcp://localhost/~/security
    username: sa
    password:
    driver-class-name: org.h2.Driver
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    use-root-path: true
    disable-swagger-default-url: true
    path: /swagger-ui
  paths-to-match:
    - /auth/**
    - /room/**
    - /schedule/**
    - /groom/**
    - /todo/**
jwt:
  access:
    expirationMs: 600000
  refresh:
    expirationDay: 14
kakao:
  client_id: 248c0f042143239e8aff41927befcf0a
  redirect_uri: http://localhost:8080/auth/kakao/login